apiVersion: v2
name: example
type: application
version: 1.14.4
dependencies:
  - name: dapr
    version: 1.14.4
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: dapr-dashboard
    version: 0.15.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: ingress-nginx
    version: 4.11.5
    repository: oci://ghcr.io/k0rdent/catalog/charts
