apiVersion: v2
name: cluster-api-provider-kubevirt
description: A Helm chart for Cluster API provider KubeVirt
type: application
version: 0.2.1
appVersion: "0.1.9"
annotations:
  cluster.x-k8s.io/provider: infrastructure-kubevirt
  cluster.x-k8s.io/v1beta1: v1beta1
dependencies:
  - name: kubevirt
    version: 0.1.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
