apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-example-USER
spec:
  template: aws-standalone-cp-{{ dash_version }}
  credential: aws-credential
  config:
    clusterLabels:
      type: aws
      group: demo
    controlPlane:
      instanceType: t3.small
    controlPlaneNumber: 1
    publicIP: false
    region: eu-central-1
    worker:
      instanceType: t3.xlarge
      rootVolumeSize: 32
    workersNumber: 1
